# 배경

## 왜 이런 것을 하게 되었나?

-   요약: **고객사의 요청**

-   부서 내 조사 프로젝트 중 한 고객사가 **전국 헬스장의 위치와 연도 별 추이 통계**를 요청함.

-   가장 경제적으로 고객사의 요구사항을 충족시킬 수 있는 방법 고안

    -   무료 공공데이터 활용

    -   부서 내 연구원이 직접 처리함으로써 타 부서 또는 협력 업체와 의사소통에 소요되는 시간 X

**고객사의 0순위 니즈를 충족시켜주자!**

-   신규 제품 및 서비스, 더 넓게는 신사업을 추진하는 과정에서 가장 먼저 필요한 것은 진출하고자 하는 시장의 현황 분석임.

-   한국갤럽의 고객사 중 자체적인 시장조사와 분석에 어려움을 겪어 수주한 조사와 함께 요청하는 경우가 많음.

    -   시장 규모, 잠재고객 규모, 경쟁 업체 수, 특정 제품군의 소비자 수 추정치 등

-   고객사의 시장조사에 대한 니즈가 분명함에도 불구하고 한국갤럽만의 뚜렷한 \`**Solution**\`이 존재하지 않음.

-   **고객사가 겪는 시장조사의 어려움에 대한 기술적인 해결책을 제시할 목적으로 본 프로젝트를 수행하게 됨.**

**고객사는 지방인허가데이터가 왜 필요할까?**

담배소매업 예시)

-   담배제조사에게 담배소매점은 소비자에게 자사 제품이 전달되는 마지막 채널

-   각 지역별 담배소매업 현황을 파악하여 판매량 예측 또는 판매량에 따른 대응 가능

    -   특정 지역에서 지역에서 담배 판매량이 낮은 경우 소매업 현황 파악하여 원인 찾고 개선 방안 모색

-   담배제조사는 담배제품 유통을 담당하는 담배도소매 업체와 협력하여 제품을 유통시켜야함. 이를 위해 각 지역의 유통 특성을 파악해야함.

-   지역별 담배소매업체의 위치, 수량, 경쟁 업체와 비교, 매출액 등 다른 데이터들과 함께 결합하여 분석하는 것을 통해 효과적인 제품 유통 전략을 수립하고 도소매 업체에게 공유하여 협력관계를 유지하거나 개선할 수 있음.

-   각 지역의 특성과 소비자 선호도 등을 파악하여 마케팅 전략을 수립

-   지방인허가데이터로 제공되는 병원, 미용실, 대형마트, 음식점 등 다른 업종에도 적용 가능
