# 목표

## 프로젝트의 목표 정의

**연도에 따른 업종별 인허가 수 추이 파악**

1.  부서 내 프로젝트 활용

    -   현재 진행 중인 마케팅 4실의 프로젝트(마이프로틴)에 적용

    -   2010년\~2022년 추이: 전국 체력단련장업 수 / 증감률 / 개업&폐업 추이

2.  기타 프로젝트 활용 가능성 제고

    -   체력단련장업 외 한국갤럽 프로젝트와 관련된 업종의 연도별 추이 파악

    -   타 부서(사회조사 포함)에서도 활용 가능하도록 최대한 많은 업종에 기술 적용

3.  데이터 시각화

    -   고객사 또는 조사 결과 보고서 내 쉽게 첨부할 수 있는 간편한 도구 개발

4.  인사이트

    -   비즈니스 인사이트

## 목표 달성을 위한 계획

1.  서비스 기획 및 설계: **2023년 4월 8일 \~ 2023년 4월 9일 (2일)**

2.  구현: **2023년 4월 10일 \~ 2023년 4월 12일 (3일)**

    -   데이터 로드 및 전처리

        -   체력단련업 외 4개 주요 업종 (일반음식점, 병원, 담배소매업, 대규모점포)

        -   각 업종의 .xlsx 파일 다운로드 (5개)

        -   폐업, 휴업 시기에 대한 결측치 처리

            -   폐업, 휴업 결측치의 경우 해당 시기에 대한 기준 마련

            -   조사 시점 등으로 대체

    -   분석

        -   최종 결과 도출 (R code base)

        -   기능 테스트 및 디버깅

    -   시각화

        -   Flexdashboard 라이브러리 활용한 대시보드 구현 (R)

            -   이미지 파일(.png)로 추출

3.  프로젝트 적용: **2023년 4월 13일 \~ 2023년 4월 14일 (2일)**

    -   마케팅 4실 진행 중인 프로젝트 적용

4.  리포트 작성: **2023년 4월 15일 \~ 2023년 4월 16일 (2일)**

    -   정기간행물 작성

        -   목차 및 분량 구성

        -   주간 / 월간 / 연간

        -   예시 ([바이브컴퍼니 - 썸트렌드](https://some.co.kr/magazine/home))

## 기대효과

1.  한 번의 조사 수행 과정 관점

-   고객사의 부족한 시장 조사 및 분석 보완

-   통계 수집, 그래프 제작 과정의 소요 시간 단축

2.  조직 내부 관점

-   **기술 내재화**

    -   방대한 양의 지방인허가데이터(공공데이터)를 데이터를 다룰 수 있는 기술을 확보함.

-   **파이프라인 구축**

    -   동일한 방식으로 [홈페이지](https://www.localdata.go.kr/)에 공개된 방대한 데이터를 필요에 따라 시각화 가능함.

-   **근로 시간 효율성 제고**

    -   불필요한 업무 시간을 줄임으로써 설문지 설계 등 더 중요한 업무에 더 많은 업무 시간을 사용할 수 있음.

-   **인사이트 제공**

    -   'BRIG' 리포트를 통해 연구 부서 구성원을 중심으로 비즈니스 인사이트 제공

3.  대외적 관점

-   기사 노출 빈도 제고

    -   사회적 이슈 발생 시 특정 통계를 중심으로 작성되는 기사 많음.

        -   [KB금융 "헬스장 1만개...'덤벨 이코노미' 시대 지속 성장 가능"](https://view.asiae.co.kr/article/2020101109401531692)

        -   [충북 "2026년까지 합계출산율 1.4명 달성할 것"](https://www.munhwa.com/news/view.html?no=2023040501071027045001)

    -   주기적으로 리포트를 배포함으로써 기사에 인용되는 빈도를 제고할 수 있음.

-   **오픈소스**

    -   시장 현황에 대한 분석에 대한 니즈는 분야를 막론함.

    -   공공데이터를 적절히 가공한 데이터를 공개함으써 공공에 기여함.

        -   기사, 학술, 주식 분석 리포트 등
